import type { CollectionConfig } from 'payload'
import { generateAltText, isAiEnabled } from '../lib/ai'

// Uploaded media (product images, etc.). Stored locally for now; a Supabase Storage
// (S3-compatible) adapter will be wired in a later phase, see Doc/DATA_MODEL.md.
export const Media: CollectionConfig = {
  slug: 'media',
  access: {
    read: () => true,
  },
  admin: {
    group: 'Catalog',
  },
  hooks: {
    // Auto-generate ALT text from the uploaded image via AI when it's left blank.
    beforeValidate: [
      async ({ data, req, operation }) => {
        if (!data) return data
        const incoming = (req as any).file as { data?: Buffer; mimetype?: string } | undefined
        const needsAlt = !data.alt || (typeof data.alt === 'string' && data.alt.trim() === '')
        if ((operation === 'create' || operation === 'update') && needsAlt && incoming?.data && isAiEnabled()) {
          try {
            const dataUrl = `data:${incoming.mimetype || 'image/jpeg'};base64,${incoming.data.toString('base64')}`
            const alt = await generateAltText({ imageDataUrl: dataUrl })
            if (alt) data.alt = alt
          } catch {
            // Non-fatal: leave alt empty; it can be filled manually.
          }
        }
        return data
      },
    ],
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      label: 'Alt text',
      // Auto-filled by AI on upload (see hooks). Optional so it never blocks an upload;
      // still important for SEO + accessibility (see Doc/SEO.md).
      localized: true,
      admin: {
        description: 'Auto-generated by AI from the image. Edit if you want to refine it.',
      },
    },
  ],
  upload: {
    imageSizes: [
      { name: 'thumbnail', width: 400, height: 400, position: 'centre' },
      { name: 'card', width: 768, height: 1024, position: 'centre' },
      { name: 'feature', width: 1200, height: 1600, position: 'centre' },
    ],
    mimeTypes: ['image/*'],
  },
}
